### ISSUE TITLE
如要比較2個中文列表中，2個也夾雜英文及數字，會否影響結果？

### ISSUE THREAD

**Issue by marcusau** [znwang25/fuzzychinese#5]
即fuzzychinese是否只可比較中文列表或詞語，不能替英文及數字，進行比較？

因現在大多中文句子也夾雜英文及數字

**Comment by znwang25** [comment]
目前这个版本中，如果把analyzer设置成‘char’，应该是可以允许出现英文及数字的。
```
fcm = FuzzyChineseMatch(analyzer='char')
```
如果使用''stroke' 或者‘radical’ analyzer， 英文与数字会被忽略掉。如果你觉得有必要添加这个功能，能否提供一个具体的使用情景。
